apiVersion: v1
kind: Secret
metadata:
  name: satisfactory-server
  namespace: games
type: Opaque
data:
  SATISFACTORY_PASSWORD: NTUqX2FCYkpkRA==
  SATISFACTORY_URL: c2F0aXNmYWN0b3J5LmZvdWxrZXMuY2xvdWQ=
  SATISFACTORY_PORT: Nzc3Nw==