---
apiVersion: v1
kind: Service
metadata:
  name: satisfactory-arthur
  namespace: games
  labels:
    app: satisfactory-arthur
spec:
  type: LoadBalancer
  ports:
    - port: 7778
      protocol: UDP
      name: "game"
      targetPort: 7778
    - port: 7778
      protocol: TCP
      name: "gametcp"
      targetPort: 7778
    - port: 8075
      protocol: TCP
      name: "prometheus"
      targetPort: 8075
  selector:
    app: satisfactory-arthur
