---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: satisfactory
  namespace: games
spec:
  selector:
    matchLabels:
      app: satisfactory
  serviceName: "satisfactory"
  replicas: 1
  template:
    metadata:
      labels:
        app: satisfactory
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
        - name: satisfactory
          image: wolveix/satisfactory-server:latest
          env:
            - name: DEBUG
              value: "false"
            - name: MAXPLAYERS
              value: "8"
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: SKIPUPDATE
              value: "false"
            - name: STEAMBETA
              value: "false"
              # max objects in the world
            - name: MAXOBJECTS
              value: "4162688"
          ports:
            - containerPort: 7777
              name: "game-tcp"
              protocol: TCP
            - containerPort: 7777
              name: "game-udp"
              protocol: UDP
          volumeMounts:
            - name: satisfactory-data
              mountPath: /config
        - name: prometheus
          image: ghcr.io/dfoulkes/satisfactory-prometheus-exporter:feature-build-container
          ports:
            - containerPort: 8075
              name: "prometheus"
              protocol: TCP
          env:
            # the IP of the nodeport or LB
             - name: SATISFACTORY_URL
               valueFrom:
                secretKeyRef:
                    name: satisfactory-server
                    key: SATISFACTORY_URL
            # the port exposed by the LB or NodePort
             - name: SATISFACTORY_PORT
               valueFrom:
                 secretKeyRef:
                    name: satisfactory-server
                    key: SATISFACTORY_PORT
            # the game server admin password
             - name: SATISFACTORY_PASSWORD
               valueFrom:
                  secretKeyRef:
                    name: satisfactory-server
                    key: SATISFACTORY_PASSWORD
  volumeClaimTemplates:
    - metadata:
        name: satisfactory-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 30Gi
        storageClassName: longhorn
